// dummy
export const DUMMY_SET = 'dummy/DUMMY_SET';
export const DUMMY_ADD_DELAY = 'dummy/DUMMY_ADD_DELAY';
export const DUMMY_ADD_DELAY_SUCCEEDED = `${DUMMY_ADD_DELAY}_SUCCEEDED`;

export const GET_CUSTOMER_SUSSCESS = 'user/GET_CUSTOMER_SUSSCESS';

export const GET_ADMINS = 'superadmins/GET_ADMINS';
export const GET_ADMINS_SUCCEEDED = `${GET_ADMINS}_SUCCEEDED`;

// me
export const SET_TOKEN = 'me/SET_TOKEN';
export const RESET_TOKEN = 'me/RESET_TOKEN';
export const SET_CREATING_BUNDLE_STATE = 'me/SET_CREATING_BUNDLE_STATE';
export const GET_PROFILE = 'me/GET_PROFILE';
export const GET_PROFILE_SUCCEEDED = `${GET_PROFILE}_SUCCEEDED`;
export const GET_MY_BUNDLES_LATEST = 'me/GET_MY_BUNDLES_LATEST';
export const GET_MY_BUNDLES_LATEST_SUCCEEDED = `${GET_MY_BUNDLES_LATEST}_SUCCEEDED`;
export const GET_MY_BUNDLES_SAVED = 'me/GET_MY_BUNDLES_SAVED';
export const GET_MY_BUNDLES_SAVED_SUCCEEDED = `${GET_MY_BUNDLES_SAVED}_SUCCEEDED`;
export const GET_MY_FOLLOWING = 'me/GET_MY_FOLLOWING';
export const GET_MY_FOLLOWING_SUCCEEDED = `${GET_MY_FOLLOWING}_SUCCEEDED`;
export const GET_MY_FOLLOWERS = 'me/GET_MY_FOLLOWERS';
export const GET_MY_FOLLOWERS_SUCCEEDED = `${GET_MY_FOLLOWERS}_SUCCEEDED`;

// bundles
export const GET_NEWEST_BUNDLES = 'bundles/GET_NEWEST_BUNDLES';
export const GET_NEWEST_BUNDLES_SUCCEEDED = `${GET_NEWEST_BUNDLES}_SUCCEEDED`;
export const GET_NEWEST_BUNDLES_STARTED = `${GET_NEWEST_BUNDLES}_STARTED`;

export const GET_NEWSFEED_BUNDLES = 'bundles/GET_NEWSFEED_BUNDLES';
export const GET_NEWSFEED_BUNDLES_SUCCEEDED = `${GET_NEWSFEED_BUNDLES}_SUCCEEDED`;
export const GET_NEWSFEED_BUNDLES_STARTED = `${GET_NEWSFEED_BUNDLES}_STARTED`;

export const GET_DISCOVER_BUNDLES = 'bundles/GET_DISCOVER_BUNDLES';
export const GET_DISCOVER_BUNDLES_SUCCEEDED = `${GET_DISCOVER_BUNDLES}_SUCCEEDED`;
export const GET_DISCOVER_BUNDLES_STARTED = `${GET_DISCOVER_BUNDLES}_STARTED`;

export const GET_RELEVANT_BUNDLES = 'bundles/GET_RELEVANT_BUNDLES';
export const GET_RELEVANT_BUNDLES_SUCCEEDED = `${GET_RELEVANT_BUNDLES}_SUCCEEDED`;
export const GET_RELEVANT_BUNDLES_STARTED = `${GET_RELEVANT_BUNDLES}_STARTED`;

export const GET_BUNDLE = 'bundles/GET_BUNDLE';
export const GET_BUNDLE_SUCCEEDED = `${GET_BUNDLE}_SUCCEEDED`;

export const GET_BUNDLES_BY_KEYWORD = 'bundles/GET_BUNDLES_BY_KEYWORD';
export const GET_BUNDLES_BY_KEYWORD_SUCCEEDED = `${GET_BUNDLES_BY_KEYWORD}_SUCCEEDED`;
export const GET_BUNDLES_BY_KEYWORD_STARTED = `${GET_BUNDLES_BY_KEYWORD}_STARTED`;

export const UPDATE_ACTIVE_BUNDLE_STATUS =
  'bundles/UPDATE_ACTIVE_BUNDLE_STATUS';

// user
export const GET_USER_INFORMATION = 'users/GET_USER_INFORMATION';
export const GET_USER_INFORMATION_SUCCEEDED = `${GET_USER_INFORMATION}_SUCCEEDED`;
export const GET_USER_BUNDLES = 'users/GET_USER_BUNDLES';
export const GET_USER_BUNDLES_SUCCEEDED = `${GET_USER_BUNDLES}_SUCCEEDED`;
export const GET_USER_FOLLOWERS = 'users/GET_USER_FOLLOWERS';
export const GET_USER_FOLLOWERS_SUCCEEDED = `${GET_USER_FOLLOWERS}_SUCCEEDED`;
export const GET_USER_FOLLOWING = 'users/GET_USER_FOLLOWING';
export const GET_USER_FOLLOWING_SUCCEEDED = `${GET_USER_FOLLOWING}_SUCCEEDED`;
export const SET_USER_BUNDLES_LOADING = 'users/SET_USER_BUNDLES_LOADING';
